[SystemSettings]
; https://dev.epicgames.com/documentation/en-us/unreal-engine/high-dynamic-range-display-output-in-unreal-engine
;
; In addition to these, you should also check GameUserSettings for:
;
;bUseHDRDisplayOutput=False
;HDRDisplayOutputNits=1000
;
; And try changing them to see what if any effect they have

; Leave both on
r.AllowHDR=1
r.HDR.EnableHDROutput=1

; ColorGamut=2 is Rec.2020 and should probably stay that way
r.HDR.Display.ColorGamut=2

; See the main reference. Try 5 and 6 first for 1k and 2k nit scRGB
r.HDR.Display.OutputDevice=6

r.HDR.Display.MaxLuminance=2320

; Should probably stay at the defaults of Mid=15 and MinLog10=-4
r.HDR.Display.MidLuminance=15
r.HDR.Display.MinLuminanceLog10=-4

; May need to play around with these for the UI
r.HDR.UI.CompositeMode=1.0
r.HDR.UI.Level=1
r.HDR.UI.Luminance=203
